### ISSUE TITLE
I Need dark Mode

### ISSUE THREAD

**Issue by SahityaRoy** [SahityaRoy/Hacktoberfest_Practice_Contribution#1]
Hey guys if you can enable dark mod then feel free to comment and fork the repo.

**Comment by neeraj15022001** [comment]
I would like to implement.

**Comment by neeraj15022001** [comment]
Also please add **enhacement** label to it. Thanks !

**Comment by SahityaRoy** [comment]
> Also please add **enhacement** label to it. Thanks !

Hey @neeraj15022001 Please check your code i merged your code but its not working.

**Comment by neeraj15022001** [comment]
I will check

**Comment by neeraj15022001** [comment]
@SahityaRoy i just opened live website it's working as expected. If not working in your case, please try opening in incognito and if still not working send me a screen recording.

**Comment by neeraj15022001** [comment]
@SahityaRoy please close this issue as it is resolved.
